name: Deployment

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Wheel building for ${{ matrix.python-version[1] }}-${{ matrix.os[1] }}_${{ matrix.os[2] }}
    runs-on: ${{ matrix.os[0] }}

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - [ "3.8", "cp38" ]
          # - [ "3.9", "cp39" ]
          - [ "3.10", "cp310" ]
          # - [ "3.11", "cp311" ]

        os:
          - [ubuntu-20.04, manylinux, x86_64]
          # - [ubuntu-20.04, manylinux, i686]
          - [macos-11, macosx, x86_64]
          - [windows-2019, win, amd64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install openmp
        if: startsWith(matrix.os[0], 'macos')
        run: |
          brew install llvm
          brew install libomp

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version[0] }}

      - name: Setup build system
        run: pip install cibuildwheel Cython

      - name: Build wheel for macOS
        if: startsWith(matrix.os[0], 'macos')
        # uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BUILD: ${{ matrix.python-version[1] }}-${{ matrix.os[1] }}_universal2
          CIBW_ARCHS_MACOS: x86_64 arm64
          MACOSX_DEPLOYMENT_TARGET: "10.14"
        run: cibuildwheel --output-dir wheelhouse

      - name: Build wheel for Linux or Windows
        if: ${{ !startsWith(matrix.os[0], 'macos') }}
        # uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BUILD: ${{ matrix.python-version[1] }}-${{ matrix.os[1] }}*
          CIBW_ARCHS: ${{ matrix.os[2] }}
        run: cibuildwheel --output-dir wheelhouse

      - name: Wheelhouse
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python-version[0] }}-${{ matrix.os[1] }}_${{ matrix.os[2] }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          # TODO: which is best? currently lowest "supported"
          python-version: "3.8"

      - name: Fetch database files
        run: |
          pip install gdown
          gdown --folder https://drive.google.com/drive/folders/1sWTHWRqzglWOjTMwNa_aqkKT__Y7Snmq?usp=sharing
          mv ./package/chebi.db ./pymantra/namemapping/databases/ChEBI/
          mv ./package/hmdb.db ./pymantra/namemapping/databases/HMDB/
          mv ./package/mantra.db ./pymantra/namemapping/databases/mantra_db/
          mv ./package/reactome.db ./pymantra/namemapping/databases/Reactome/
          rm -r ./package

      - name: Build sdist
        run: |
          pip install --upgrade wheel setuptools Cython
          python setup.py sdist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pymantra
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          verbose: true
