name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install package
        run: |
          pip install Cython
          pip install .[dev]
          python setup.py build_ext --inplace
          cp .env.template .env

      - name: Run unit tests with coverage
        run: python -m pytest --cov-report=xml --cov=pymantra

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV }}
          files: ./coverage/coverage.xml
